// Code generated by coz. DO NOT EDIT.
/**
 * Browser entrypoint for the-framework
 * @module the-entrypoint
 */
'use strict'

import history from './history'
import mount from './mount'
import workers from './workers'

export {
  history,
  mount,
  workers,
}

