// Code generated by coz. DO NOT EDIT.
/**
 * Browser entrypoint for the-framework
 * @module the-entrypoint
 */
'use strict'

const _interopRequireDefault = (obj) => obj && obj.__esModule ? obj : {default: obj}
const _d = (m) => _interopRequireDefault(m).default

// --------------
// Named exports for lebab ( https://github.com/lebab/lebab )
// --------------
exports.history = _d(require('./history'))
exports.mount = _d(require('./mount'))
exports.singleton = _d(require('./singleton'))
exports.workers = _d(require('./workers'))

// --------------
// Default exports
// --------------
module.exports = {
  get history () { return _d(require('./history')) },
  get mount () { return _d(require('./mount')) },
  get singleton () { return _d(require('./singleton')) },
  get workers () { return _d(require('./workers')) },
}
