// Code generated by coz. DO NOT EDIT.
/**
 * Browser entrypoint for the-framework
 * @module the-entrypoint
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const history_ = require('./history')
const mount_ = require('./mount')
const patch_ = require('./patch')
const secure_ = require('./secure')
const singleton_ = require('./singleton')
const workers_ = require('./workers')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.history = _d(history_)
exports.mount = _d(mount_)
exports.patch = _d(patch_)
exports.secure = _d(secure_)
exports.singleton = _d(singleton_)
exports.workers = _d(workers_)

module.exports = {
  history: _d(history_),
  mount: _d(mount_),
  patch: _d(patch_),
  secure: _d(secure_),
  singleton: _d(singleton_),
  workers: _d(workers_),
}
