// Code generated by coz. DO NOT EDIT.
/**
 * Browser entrypoint for the-framework
 * @module the-entrypoint
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const history_ = require('./history')
const mount_ = require('./mount')
const secure_ = require('./secure')
const singleton_ = require('./singleton')
const workers_ = require('./workers')


exports.history = _d(history_)
exports.mount = _d(mount_)
exports.secure = _d(secure_)
exports.singleton = _d(singleton_)
exports.workers = _d(workers_)
